# Generated by Django 5.2.1 on 2025-05-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
