# Generated by Django 5.2.1 on 2025-05-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Almacen del producto', max_length=100),
        ),
    ]
