# Generated by Django 5.2.1 on 2025-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0006_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Codigo unico para cada producto', max_length=50, null=True),
        ),
    ]
