# Generated by Django 5.2.1 on 2025-05-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('encargado', 'Encargado de Almacen'), ('consulta', 'Usuario de Consulta')], default='consulta', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
